### ISSUE TITLE
globalConfig.json version error

### ISSUE THREAD

**Issue by tsullivan06** [tmartin14/ucc_migration_test#3]
I was getting a version checking error when running the convert script:
-----------------------------------------------------------------------
Version Checking
    appserver/static/js/build/globalConfig.json --> 3.2.1,
    app.manifest                                --> 3.2.1
    default/app.conf                            --> 3.2.1

ERROR:   Versions are out of synch.  Please edit so that all 3 files reflect the same version number
Exiting now

Looks like the regex was picking up the ',' after the version number in the globalConfig.json file. I changed line 385 to read: 

CURR_VERSION=`grep "version" ./globalConfig.json | grep -o '[^: d]*$' | sed 's/,//;s/"//g'` 

Which seems to have resolved that issue:
Version Checking
    appserver/static/js/build/globalConfig.json --> 3.2.1
    app.manifest                                --> 3.2.1
    default/app.conf                            --> 3.2.1
all version settings match

**Comment by tmartin14** [comment]
Thanks for the update.  I've updated the repo accordingly.

**Comment by tsullivan06** [comment]
Hey Tom -

So my fix was somewhat successful but I did run into additional gremlins:

1. This one is a 'it might happen' but it just so happens that I use a variable name with '_version' in it in my globalconfig.json file. The regex is actually picking this up so I had to modify grep to only return the first match.
2. The other gremlin that I ran into is when the current and the app manifest versions are pulled out there's a trailing space or other character (result of the sed command?). The app conf version didn't appear to have it, could be the lack of quotes/comma. The result was current & manifest variables were 6 characters long and the manifest variable was 5. (A cmp check said that the 6th character was the difference which looked like a blank space). Since the length didn't match the version check kept on failing. 

The reworked variable configurations that I was able to get to work successfully:

_CURR_VERSION=`grep "version" ./globalConfig.json | grep -m 1 -o '[^: d]*$' | sed 's/,//;s/"//g'  | sed 's/.$//' `_ 
    ** added ` | sed 's/.$//' ` to drop off the trailing space/character

_APP_CONF_VER=`grep '^version' ./package/default/app.conf | grep -o '[^: d]*$' `_ 
    ** removed ` | sed 's/,$//;s/"//g' ` not really necessary, mostly did it because it helped me remember the difference between the 3 and since it wasn't necessary I didn't want to tempt by Irish buddy Murphy

_APP_MANIFEST_VER=`grep 'version' ./package/app.manifest  | grep -o '[^: d]*$' | sed 's/,$//;s/"//g'| sed 's/.$//'`_
   ** added ` | sed 's/.$//' ` to drop off the trailing space/character     (Same as CURR_VERSION)

Thanks for creating this! Looking forward to using it on a bunch of my add-ons.

**Comment by tsullivan06** [comment]
Ended up putting in some if and while clauses incase there were training values over 5, for example:
if [ ${#CURR_VERSION} > 5 ]; 
  then
    number_over=$((${#CURR_VERSION} - 5 ))
    echo $number_over
    while [ $number_over -gt 0 ];do
      echo "Current verions length is not 5 characters, removing last character"
      CURR_VERSION=`echo "$CURR_VERSION" | sed 's/.$//' `
      number_over=$((${#CURR_VERSION} - 5 ))
    done
  else
    echo
    echo "Current Version length looks correct" 
fi
